### PR TITLE
Cascading menu with PAPI metrics

### PR DESCRIPTION
**Pull request by sayefsakin**
For the PAPI metrics, I removed the rate calculation since there is no PAPI_TOT_CYC metric on the trace file and the rate is not relevant to other metrics. Now, only related values are presented on y-axis and it is drawn as a scatter-plot. Since on the trace file, for same location, all values are same for each metric.

### CODE REVIEW

**Comment by kisaacs** [comment]
I'm confused.

1. What happens when there is PAPI_TOT_CYC in the trace file
2. Rate is relevant to other PAPI counters as they are collected the same way
3. What does "related values" mean?
4. Which trace file are you speaking about? I don't think this generalizes

Thanks

**Comment by sayefsakin** [comment]
1. It will generate as a scatter plot.
2.  I am getting weird types of lines for the rates of other metrics, check the picture.
3. "VALUE" field in the line "METRIC" 
4. this one `http://www.nic.uoregon.edu/~khuck/Phylanx/lra_csv_2019-12-05.tgz` from Kevin.

I'll investigate more on the lines and try to fix it.
Capture

**Comment by sayefsakin** [comment]
In the last comit, I've fixed the line chart for PAPI metrics and golden layout problems. 
Just found another artifact with the golden layout. I tried to put respective metric name on the title. At first, the window title shows metric name correctly. But when I start dragging any window, the title changes to its default name.

**Comment by alex-r-bigelow** [comment]
@sayefsakin, you can go ahead and merge this

**Pull request merged**
